import { Barlow } from 'next/font/google';
import './globals.css';

export const metadata = {
  title: 'Sunnyside Agency Landing Page',
  description: 'Generated by create next app',
};

const barlow = Barlow({ weight: '600', subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
        {children}
      </body>
    </html>
  );
}
